BN:
  WEIGHT_DECAY: 0.0
TRAIN:
  ENABLE: True
  DATASET: KineticsSounds
  NUM_SAMPLES: 10
  BATCH_SIZE: 5
  SAVE_EVERY_EPOCH: 30
  TEST_PERIOD: 1
  PREEMPTIBLE: False
VAL:
  ENABLE: False
  DATASET: KineticsSounds
TEST:
  ENABLE: False
  DATASET: KineticsSounds
  NUM_SAMPLES: 30
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
  BATCH_SIZE: 5
VIS:
  ARCH: resnet
  MODEL_NAME: ResNet
RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  SPATIAL_STRIDES: [[1], [2], [2], [2]]
  SPATIAL_DILATIONS: [[1], [1], [1], [1]]
AUD:
  ARCH: resnet
  MODEL_NAME: AudioResNet
AUDIO_RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 32
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  STRIDES: [2, 2, 2, 2]
  DILATIONS: [1, 1, 1, 1]
MODEL:
  TASK: MultimodalSequenceClassify
  DOWNSTREAM_FUSION: concat
  FC_INIT_STD: 0.01
  ZERO_INIT_FINAL_BN: True
  EPSILON: 1e-5
  MOMENTUM: 0.1
  NUM_CLASSES: 32
  DROPOUT_RATE: 0.5
  POOLING: True
  LOSS_FUNC: cross_entropy
  HEAD_ACT: softmax
  ARCH: visual_audio
  FUSION: mid
  USE_TRANSFORMER: True
TRANSFORMER:
  ATTENTION_PROBS_DROPOUT_PROB: 0.1
  HIDDEN_ACT: gelu
  HIDDEN_DROPOUT_PROB: 0.1
  HIDDEN_SIZE: 768
  INITIALIZER_RANGE: 0.02
  INTERMEDIATE_SIZE: 3072
  MAX_POSITION_EMBEDDINGS: 22
  NUM_ATTENTION_HEADS: 12
  NUM_HIDDEN_LAYERS: 6
  NUM_HIDDEN_GROUPS: 1
  NET_STRUCTURE_TYPE: 0
  GAP_SIZE: 0
  NUM_MEMORY_BLOCKS: 0
  INNER_GROUP_NUM: 1
  DOWN_SCALE_FACTOR: 1
  TYPE_VOCAB_SIZE: 2
  OUTPUT_HIDDEN_STATES: False
  USE_MEAN_POOLING: False
  SHARING_ACROSS_LAYERS: True
  SHARING_ACROSS_MODELS: True
  USE_DECOMPOSITION: True
  ORTHOGONAL_SIZE: 128
  ORTHOGONAL_MODE: static
  ORTHOGONAL_INIT: cayley
  ORTHOGONAL_K: 100
DATA:
  CROP_SIZE: 112
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TARGET_FPS: 30
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  TRAIN_CROP_SIZE: 112
  TRAIN_JITTER_SCALES: [128, 160]
  TEST_CROP_SIZE: 128
  TARGET_AUDIO_RATE: 44100
  AUDIO_FREQUENCY: 80
  AUDIO_TIME: 128
  FREQUENCY_MASK_RATE: 0.05
  TIME_MASK_RATE: 0.05
  TRANSFORMATIONS: ["resize_crop", "flip", "color_normalize"]
  SEQUENCE_LENGTH: 10
SOLVER:
  BASE_LR: 0.001
  FINETUNE_LR: 0.0001
  PROTOCOL: finetune
  LR_POLICY: linear
  MAX_EPOCH: 20
  WEIGHT_DECAY: 5e-6
  FINETUNE_WEIGHT_DECAY: 5e-6
  WARMUP_START_LR: 0.0
  WARMUP_START_FINETUNE_LR: 0.0
  WARMUP_EPOCHS: 0
  OPTIMIZING_METHOD: adam
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
LOG_PERIOD: 50
