BN:
  WEIGHT_DECAY: 0.0
TRAIN:
  ENABLE: True
  DATASET: ESC50
  DATASET_SPLIT: 1
  NUM_SAMPLES: 10
  BATCH_SIZE: 128
  SAVE_EVERY_EPOCH: 500
  TEST_PERIOD: 1
  PREEMPTIBLE: False
VAL:
  ENABLE: False
  DATASET: ESC50
  DATASET_SPLIT: 1
TEST:
  ENABLE: False
  DATASET: ESC50
  DATASET_SPLIT: 1
  NUM_SAMPLES: 10
  BATCH_SIZE: 128
AUD:
  ARCH: resnet
  MODEL_NAME: AudioResNet
AUDIO_RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 32
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  STRIDES: [2, 2, 2, 2]
  DILATIONS: [1, 1, 1, 1]
MODEL:
  TASK: AudioClassify
  DOWNSTREAM_FUSION: late
  FC_INIT_STD: 0.01
  ZERO_INIT_FINAL_BN: True
  EPSILON: 1e-5
  MOMENTUM: 0.1
  NUM_CLASSES: 50
  DROPOUT_RATE: 0.1
  POOLING: True
  LOSS_FUNC: multi_margin
  MARGIN: 0.1
  HEAD_ACT: softmax
  USE_TRANSFORMER: False
DATA:
  CLIP_DURATION: 2
  TARGET_AUDIO_RATE: 44100
  AUDIO_FREQUENCY: 80
  AUDIO_TIME: 128
  FREQUENCY_MASK_RATE: 0.05
  TIME_MASK_RATE: 0.05
SOLVER:
  BASE_LR: 0.003
  FINETUNE_LR: 0.0
  PROTOCOL: linear_eval
  LR_POLICY: linear
  MAX_EPOCH: 300
  WEIGHT_DECAY: 5e-6
  FINETUNE_WEIGHT_DECAY: 0.0
  WARMUP_START_LR: 0.0
  WARMUP_START_FINETUNE_LR: 0.0
  WARMUP_EPOCHS: 0
  OPTIMIZING_METHOD: adam
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
LOG_PERIOD: 50
